### ISSUE TITLE
Make the interfaces of the cryptography algorithms consistent

### ISSUE THREAD

**Issue by ChengYuHsu** [ISS-Security/hw_3-credit_card_crypto#5]
Hi Soumya,

After taking a look at the `double_trans_cipher.rb` and `aes_cipher.rb`, I found it difficult to DRY out the `spec/crypto_spec.rb` since the order of the arguments are not consistent with those in `substitution_cipher.rb`.

#### `double_trans_cipher.rb`

```ruby
module DoubleTranspositionCipher
  def encrypt(key)
    # implementation
  end
  def Decrypt()
    # implementation
  end
end
```

The only way I knew to invoke `encrypt` and `decrypt` is *mixin* (am I correct ? ).

Btw, should `decrypt` in `DoubleTranspositionCipher` also take a `key` as parameter (for the PRNG).

#### `aes_cipher.rb`

```ruby
require 'openssl'

module AesCipher
  def self.encrypt(key, plaintext)
    # implementation
  end
  def self.decrypt(key, aes_crypt)
    # # implementation
  end
end
```

This looks pretty good. However, the order of the arguments is opposite to the order in `substitution_cipher.rb` which is defined as:

```ruby
self.encrypt(doc, key)
  # implementation
end
```

So, is it possible to change the method definitions? 

\- Cheng-Yu

**Comment by soumyaray** [comment]
yes it is possible!  I’ll do this in the morning on the files I’ve suppled.




thanks,




Soumya


(null)
