### ISSUE TITLE
About hash collisions

### ISSUE THREAD

**Issue by ChengYuHsu** [ISS-Security/hw_3-credit_card_crypto#7]
Hi Professor,

In part D of the assignment, we're going to write our own test cases for the hash function.
However, something looks weird in `spec/hash_spec.rb`:

```ruby
  it 'should produce different hashes for different information' do
    # TODO: implement this test
  end
```

This test case is designed to test that different hashes will be generated if different information is given, which is not necessary true.

As I know, there exists some hash collisions (although the probability is extremely small) that may cause failure on this test case.

So should we ignore the probability of collisions or delete this test case?

\- Cheng-Yu

**Comment by soumyaray** [comment]
Great question!!!


Yes, hash collisions are possible but should be very unlikely. Thus, let’s go ahead with the test as it is.  A more rigorous test might involved hashing a large amount of random data and making sure that < 0.1% of collisions occur.  However, my **feeling** is that this would be over-engineering the problem at hand right now.  We can go back and fix our tests if hash collisions are so likely.




Notice that hash collisions for the secure_hash should be impossible (for all practical purposes) by accident.




Hope this helps.

**Comment by ChengYuHsu** [comment]
Got it.
Thanks for the explanation!
